name: Todo_MVC
description: A sample Dart application with Web UI.
homepage: https://github.com/dart-lang/web-ui/tree/master/example/todomvc
dependencies:
  browser: any
  web_ui: any
dev_dependencies:
  unittest: any
